[package]
name = "ppf"
version = "0.1.0"
authors = ["makyos <makyos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lopdf = "0.26.0"

